# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='last_accessed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
